export default Object.freeze({
	// onboarding
	WELCOME_SCREEN: 'WELCOME_SCREEN',
	SIGN_UP_SCREEN: 'SIGN_UP_SCREEN',
	SIGN_IN_SCREEN: 'SIGN_IN_SCREEN',
	OTP_VERIFY_SCREEN: 'OTP_VERIFY_SCREEN',

	// Main Pages
	TAB_HOME_SCREEN: 'TAB_HOME_SCREEN',
	TAB_MOMENT_SCREEN: 'TAB_MOMENT_SCREEN',
	TAB_SERVICES_SCREEN: 'TAB_SERVICES_SCREEN',
	TAB_CHAT_SCREEN: 'TAB_CHAT_SCREEN',
	TAB_SETTING_SCREEN: 'TAB_SETTING_SCREEN',
});
